import java.sql.*;
import java.util.*;
import javax.swing.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rupak
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayerList = new javax.swing.JFrame();
        playerlistCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        playerInfoBTN = new javax.swing.JButton();
        bid1BTN = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ownerLB = new javax.swing.JLabel();
        PlayerInfo = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        pidLB = new javax.swing.JLabel();
        pnameLB = new javax.swing.JLabel();
        roleLB = new javax.swing.JLabel();
        baseLB = new javax.swing.JLabel();
        updatedLB = new javax.swing.JLabel();
        statusLB = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tidLB = new javax.swing.JLabel();
        Bid = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        playerIDLB = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        playerNameLB = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rolesLB = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bpLB = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        statLB = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        currBidLB = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        confirmBidBTN = new javax.swing.JButton();
        bidBackBTN = new javax.swing.JButton();
        newBidTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        teamIDLB = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        teamIDTF = new javax.swing.JTextField();
        UpdatedInfo = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        upPlayerIDLB = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        upPlayerNameLB = new javax.swing.JLabel();
        upStatLB = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        prevBidLB = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        updatedBidLB = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        prevTeamIDLB = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        updatedTeamIDLB = new javax.swing.JLabel();
        confirmPayBTN = new javax.swing.JButton();
        updatedInfoBTN = new javax.swing.JButton();
        walletStatusBTN = new javax.swing.JButton();
        WalletInfo = new javax.swing.JFrame();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        walletOldLB = new javax.swing.JLabel();
        walletNewLB = new javax.swing.JLabel();
        walletInfoBTN = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        ownerIDTF = new javax.swing.JTextField();
        walletBTN = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        numberTF = new javax.swing.JTextField();
        Payment = new javax.swing.JFrame();
        paymentBTN = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        DebitcardjRadioButton = new javax.swing.JRadioButton();
        CreditcardjRadioButton = new javax.swing.JRadioButton();
        NetbankingjRadioButton = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        PaytmjRadioButton = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        Cardnumber = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        ExpiryMonth = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        ExpiryYear = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        Nameoncard = new javax.swing.JTextField();
        CVV = new javax.swing.JPasswordField();
        Final = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        bidAgainBTN = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        loginBTN = new javax.swing.JButton();

        PlayerList.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        PlayerList.setTitle("Player List");
        PlayerList.setMinimumSize(new java.awt.Dimension(402, 238));
        PlayerList.setSize(new java.awt.Dimension(402, 300));

        playerlistCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "K L Rahul", "Virat Kohli", "Yashaswi Jaiswal", "Ravi Bishnoi", "Jasprit Bumrah", "Ravindra Jadeja", "Devdutt Padikkal", "KS Bharat", "Glenn Maxwell", "Rashid Khan", "Arshdeep Singh", "Rishabh Pant", "AB DeVilliers", "Yuzendra Chahal", "Varun Charkravarthy", "<end>" }));
        playerlistCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerlistCBActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Player List");

        playerInfoBTN.setForeground(new java.awt.Color(51, 51, 255));
        playerInfoBTN.setText("Player Info>>");
        playerInfoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerInfoBTNActionPerformed(evt);
            }
        });

        bid1BTN.setForeground(new java.awt.Color(51, 51, 255));
        bid1BTN.setText("Bid now>>");
        bid1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bid1BTNActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        jLabel11.setText("                  Welcome!");

        javax.swing.GroupLayout PlayerListLayout = new javax.swing.GroupLayout(PlayerList.getContentPane());
        PlayerList.getContentPane().setLayout(PlayerListLayout);
        PlayerListLayout.setHorizontalGroup(
            PlayerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerListLayout.createSequentialGroup()
                .addGroup(PlayerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayerListLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(PlayerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(playerlistCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PlayerListLayout.createSequentialGroup()
                                .addComponent(playerInfoBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(bid1BTN))))
                    .addGroup(PlayerListLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayerListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PlayerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayerListLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayerListLayout.createSequentialGroup()
                        .addComponent(ownerLB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
        );
        PlayerListLayout.setVerticalGroup(
            PlayerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ownerLB, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(playerlistCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(PlayerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerInfoBTN)
                    .addComponent(bid1BTN))
                .addGap(34, 34, 34))
        );

        PlayerInfo.setTitle("Player Information");
        PlayerInfo.setSize(new java.awt.Dimension(380, 360));

        jLabel4.setText("Player ID:");

        jLabel5.setText("Player Name:");

        jLabel6.setText("Role:");

        jLabel7.setText("Base price:");

        jLabel8.setText("Updated price:");

        jLabel9.setText("Status:");

        backBTN.setForeground(new java.awt.Color(51, 51, 255));
        backBTN.setText("Back>>");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        jLabel10.setText("Team ID:");

        javax.swing.GroupLayout PlayerInfoLayout = new javax.swing.GroupLayout(PlayerInfo.getContentPane());
        PlayerInfo.getContentPane().setLayout(PlayerInfoLayout);
        PlayerInfoLayout.setHorizontalGroup(
            PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerInfoLayout.createSequentialGroup()
                .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayerInfoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(PlayerInfoLayout.createSequentialGroup()
                                .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pidLB, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayerInfoLayout.createSequentialGroup()
                                        .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(updatedLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(baseLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(roleLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pnameLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(8, 8, 8))
                                    .addComponent(tidLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(statusLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(PlayerInfoLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(backBTN)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        PlayerInfoLayout.setVerticalGroup(
            PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerInfoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(pidLB, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(pnameLB, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(roleLB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(baseLB, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(updatedLB, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(statusLB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(tidLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(backBTN)
                .addGap(26, 26, 26))
        );

        Bid.setTitle("Bid");
        Bid.setSize(new java.awt.Dimension(442, 520));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel12.setText("BID");

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel13.setText("Player Information");

        jLabel14.setText("Player ID:");

        jLabel16.setText("Player Name:");

        jLabel18.setText("Roles:");

        jLabel20.setText("Base Price:");

        jLabel22.setText("Status:");

        jLabel24.setText("Current Bid:");

        jLabel26.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel26.setText("Please enter the new bid!");

        jLabel27.setText("New bid amount:");

        confirmBidBTN.setForeground(new java.awt.Color(0, 51, 255));
        confirmBidBTN.setText("Confirm Bid>>");
        confirmBidBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBidBTNActionPerformed(evt);
            }
        });

        bidBackBTN.setForeground(new java.awt.Color(0, 51, 255));
        bidBackBTN.setText("Back>>");
        bidBackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidBackBTNActionPerformed(evt);
            }
        });

        jLabel15.setText("Team ID:");

        jLabel21.setText("Enter your team ID:");

        javax.swing.GroupLayout BidLayout = new javax.swing.GroupLayout(Bid.getContentPane());
        Bid.getContentPane().setLayout(BidLayout);
        BidLayout.setHorizontalGroup(
            BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BidLayout.createSequentialGroup()
                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BidLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel12))
                    .addGroup(BidLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel13))
                    .addGroup(BidLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(bidBackBTN)
                        .addGap(49, 49, 49)
                        .addComponent(confirmBidBTN))
                    .addGroup(BidLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BidLayout.createSequentialGroup()
                                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(playerIDLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(playerNameLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rolesLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bpLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(statLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(currBidLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(teamIDLB, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)))
                            .addGroup(BidLayout.createSequentialGroup()
                                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel27))
                                .addGap(18, 18, 18)
                                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newBidTF, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teamIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(BidLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        BidLayout.setVerticalGroup(
            BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(playerIDLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(playerNameLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rolesLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bpLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(statLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(currBidLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teamIDLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(24, 24, 24)
                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(teamIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bidBackBTN)
                    .addComponent(confirmBidBTN))
                .addContainerGap())
        );

        UpdatedInfo.setTitle("Updated Information");
        UpdatedInfo.setPreferredSize(new java.awt.Dimension(408, 410));
        UpdatedInfo.setSize(new java.awt.Dimension(408, 410));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel17.setText("                             Updated Information");

        jLabel19.setText("Player ID:");

        jLabel23.setText("Player Name:");

        jLabel28.setText("Status:");

        jLabel30.setText("Previous Bid:");

        jLabel32.setText("Updated Bid:");

        jLabel34.setText("Previous Team ID:");

        jLabel36.setText("Updated Team ID:");

        confirmPayBTN.setForeground(new java.awt.Color(0, 51, 255));
        confirmPayBTN.setText("Confirm and Pay>>");
        confirmPayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPayBTNActionPerformed(evt);
            }
        });

        updatedInfoBTN.setForeground(new java.awt.Color(0, 51, 255));
        updatedInfoBTN.setText("Back>>");
        updatedInfoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedInfoBTNActionPerformed(evt);
            }
        });

        walletStatusBTN.setForeground(new java.awt.Color(0, 51, 255));
        walletStatusBTN.setText("Wallet Status>>");
        walletStatusBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walletStatusBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdatedInfoLayout = new javax.swing.GroupLayout(UpdatedInfo.getContentPane());
        UpdatedInfo.getContentPane().setLayout(UpdatedInfoLayout);
        UpdatedInfoLayout.setHorizontalGroup(
            UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatedInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addGroup(UpdatedInfoLayout.createSequentialGroup()
                        .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel19)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30))
                        .addGap(45, 45, 45)
                        .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upPlayerNameLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upStatLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prevBidLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upPlayerIDLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(UpdatedInfoLayout.createSequentialGroup()
                        .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel32))
                        .addGap(21, 21, 21)
                        .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prevTeamIDLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatedBidLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(UpdatedInfoLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(21, 21, 21)
                        .addComponent(updatedTeamIDLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(UpdatedInfoLayout.createSequentialGroup()
                        .addComponent(confirmPayBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(walletStatusBTN)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatedInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updatedInfoBTN)
                .addGap(161, 161, 161))
        );
        UpdatedInfoLayout.setVerticalGroup(
            UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatedInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(upPlayerIDLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(upPlayerNameLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upStatLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(prevBidLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updatedBidLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(prevTeamIDLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatedTeamIDLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(UpdatedInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPayBTN)
                    .addComponent(walletStatusBTN))
                .addGap(18, 18, 18)
                .addComponent(updatedInfoBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        WalletInfo.setTitle("Wallet Information");
        WalletInfo.setPreferredSize(new java.awt.Dimension(430, 300));
        WalletInfo.setSize(new java.awt.Dimension(430, 300));

        jLabel29.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabel29.setText("                  Wallet Information");

        jLabel31.setText("Old Wallet currency:");

        jLabel33.setText("New Wallet currency:");

        walletInfoBTN.setForeground(new java.awt.Color(0, 51, 255));
        walletInfoBTN.setText("Back>>");
        walletInfoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walletInfoBTNActionPerformed(evt);
            }
        });

        jLabel38.setText("Owner ID:");

        walletBTN.setForeground(new java.awt.Color(0, 51, 255));
        walletBTN.setText("Enter>>");
        walletBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walletBTNActionPerformed(evt);
            }
        });

        jLabel39.setText("Enter number of players:");

        javax.swing.GroupLayout WalletInfoLayout = new javax.swing.GroupLayout(WalletInfo.getContentPane());
        WalletInfo.getContentPane().setLayout(WalletInfoLayout);
        WalletInfoLayout.setHorizontalGroup(
            WalletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WalletInfoLayout.createSequentialGroup()
                .addGroup(WalletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WalletInfoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WalletInfoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(WalletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(WalletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(walletBTN)
                            .addGroup(WalletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(walletInfoBTN)
                                .addComponent(walletOldLB, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addComponent(walletNewLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(WalletInfoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(WalletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ownerIDTF)
                                    .addComponent(numberTF, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        WalletInfoLayout.setVerticalGroup(
            WalletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WalletInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WalletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(WalletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(numberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(walletBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WalletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(walletOldLB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(WalletInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(walletNewLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(14, 14, 14)
                .addComponent(walletInfoBTN)
                .addGap(18, 18, 18))
        );

        Payment.setPreferredSize(new java.awt.Dimension(482, 360));
        Payment.setSize(new java.awt.Dimension(482, 360));

        paymentBTN.setForeground(new java.awt.Color(0, 51, 255));
        paymentBTN.setText("Pay>>");
        paymentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBTNActionPerformed(evt);
            }
        });

        jLabel35.setText("Choose a mode of payment:");

        buttonGroup1.add(DebitcardjRadioButton);
        DebitcardjRadioButton.setText("Debit Card");

        buttonGroup1.add(CreditcardjRadioButton);
        CreditcardjRadioButton.setText("Credit Card");

        buttonGroup1.add(NetbankingjRadioButton);
        NetbankingjRadioButton.setText("Netbanking");
        NetbankingjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetbankingjRadioButtonActionPerformed(evt);
            }
        });

        jLabel37.setText("Enter card number:");

        buttonGroup1.add(PaytmjRadioButton);
        PaytmjRadioButton.setText("Paytm");

        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("Select>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel40.setText("Expiry Date:");

        jLabel41.setText("/");

        ExpiryYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpiryYearActionPerformed(evt);
            }
        });

        jLabel42.setText("CVV:");

        jLabel43.setText("Name on card:");

        javax.swing.GroupLayout PaymentLayout = new javax.swing.GroupLayout(Payment.getContentPane());
        Payment.getContentPane().setLayout(PaymentLayout);
        PaymentLayout.setHorizontalGroup(
            PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentLayout.createSequentialGroup()
                .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jButton2))
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(paymentBTN))
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(ExpiryMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExpiryYear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(CVV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(PaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addComponent(Nameoncard)
                        .addContainerGap())
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addContainerGap())
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(NetbankingjRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PaytmjRadioButton)
                        .addGap(37, 37, 37))
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DebitcardjRadioButton)
                            .addComponent(jLabel37))
                        .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PaymentLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Cardnumber))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaymentLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CreditcardjRadioButton)
                                .addGap(134, 134, 134))))))
        );
        PaymentLayout.setVerticalGroup(
            PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreditcardjRadioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DebitcardjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NetbankingjRadioButton)
                    .addComponent(PaytmjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(Cardnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(ExpiryMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(ExpiryYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(CVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nameoncard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addComponent(paymentBTN)
                .addGap(37, 37, 37))
        );

        Final.setTitle("Thank you");
        Final.setPreferredSize(new java.awt.Dimension(326, 160));
        Final.setSize(new java.awt.Dimension(326, 160));

        jLabel25.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel25.setText("Thank you for placing your bid!");

        bidAgainBTN.setForeground(new java.awt.Color(0, 51, 255));
        bidAgainBTN.setText("Bid again>>");
        bidAgainBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidAgainBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FinalLayout = new javax.swing.GroupLayout(Final.getContentPane());
        Final.getContentPane().setLayout(FinalLayout);
        FinalLayout.setHorizontalGroup(
            FinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalLayout.createSequentialGroup()
                .addGroup(FinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FinalLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel25))
                    .addGroup(FinalLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(bidAgainBTN)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        FinalLayout.setVerticalGroup(
            FinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bidAgainBTN)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(490, 280));

        jLabel1.setText("Login ID");

        jLabel2.setText("Password");

        loginTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTFActionPerformed(evt);
            }
        });

        loginBTN.setForeground(new java.awt.Color(51, 51, 255));
        loginBTN.setText("Login>>");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginBTN)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginTF, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loginTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(loginBTN)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTFActionPerformed

    }//GEN-LAST:event_loginTFActionPerformed

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
String loginid=loginTF.getText();
String password=new String(passwordTF.getPassword());
try{
Class.forName("java.sql.Driver");
Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ipl","root","Dragon@2002");
Statement stmt=(Statement)con.createStatement();
      String query="select * from logindetails natural join owner where LoginID='"+loginid+"'and Password='"+password+"';";
      ResultSet rs=(ResultSet)stmt.executeQuery(query);
        if(rs.next())
        {
            String owner1=rs.getString("OFirstName");
            String owner2=rs.getString("OLastName");
            ownerLB.setText(owner1+" "+owner2);
            PlayerList.setVisible(true);
        }
           else
            {
               JOptionPane.showMessageDialog(this,"Enter the valid login credentials!"); 
            }
        }
catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_loginBTNActionPerformed

    private void playerlistCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerlistCBActionPerformed

    }//GEN-LAST:event_playerlistCBActionPerformed

    private void playerInfoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerInfoBTNActionPerformed
String s=(String)playerlistCB.getSelectedItem();
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipl","root","Dragon@2002");
Statement stmt=con.createStatement();
      String query="select * from player where PlayerName='"+s+"';";
      ResultSet rs=stmt.executeQuery(query);
        if(rs.next()){
            String pID=rs.getString("PlayerId");
            String role=rs.getString("Roles");
            String base=rs.getString("BasePrice");
            String updated=rs.getString("UpdatedPrice");
            String stat=rs.getString("Status");
            String tID=rs.getString("TeamID");
            pidLB.setText(pID);
            pnameLB.setText(s);
            roleLB.setText(role);
            baseLB.setText(base);
            updatedLB.setText(updated);
            statusLB.setText(stat);
            tidLB.setText(tID);
            PlayerInfo.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Select a valid option!"); 
        }
        }
catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_playerInfoBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
PlayerInfo.setVisible(false);
PlayerList.setVisible(true);
    }//GEN-LAST:event_backBTNActionPerformed

    private void confirmBidBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBidBTNActionPerformed
String s=(String)playerlistCB.getSelectedItem();
String s1=newBidTF.getText();
int bidamount=Integer.parseInt(s1);
if(bidamount<0){
    JOptionPane.showMessageDialog(null,"Please enter a valid bid amount!");
}
else{
String tid=teamIDTF.getText();
if(!(tid.equals("1") || tid.equals("2") || tid.equals("3") || tid.equals("4") || tid.equals("5"))){
    JOptionPane.showMessageDialog(null,"Please enter a valid team ID!");
}
else{
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipl","root","Dragon@2002");
Statement stmt=con.createStatement();
      String query2="select * from player where PlayerName='"+s+"';";
      ResultSet rs1=stmt.executeQuery(query2);
        if(rs1.next()){
            String pr=rs1.getString("UpdatedPrice");
            String upTID=rs1.getString("TeamID");
            prevBidLB.setText(pr);
            prevTeamIDLB.setText(upTID);
        }
      String query1="update player set updatedprice=updatedprice+"+s1+",teamid="+tid+" where playername='"+s+"';";
      stmt.executeUpdate(query1);
      String query="select * from player where PlayerName='"+s+"';";
      ResultSet rs=stmt.executeQuery(query);
        if(rs.next()){
            String pID=rs.getString("PlayerId");
            String pName=rs.getString("PlayerName");
            String stat=rs.getString("Status");
            String upBid=rs.getString("UpdatedPrice");
            String upTID=rs.getString("TeamID");
            upPlayerIDLB.setText(pID);
            upPlayerNameLB.setText(pName);
            upStatLB.setText(stat);
            updatedBidLB.setText(upBid);
            updatedTeamIDLB.setText(upTID);
        }
        }
catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}
UpdatedInfo.setVisible(true);
}
}
    }//GEN-LAST:event_confirmBidBTNActionPerformed

    private void bid1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bid1BTNActionPerformed
String s=(String)playerlistCB.getSelectedItem();
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipl","root","Dragon@2002");
Statement stmt=con.createStatement();
      String query="select * from player where PlayerName='"+s+"';";
      ResultSet rs=stmt.executeQuery(query);
        if(rs.next()){
            String pID=rs.getString("PlayerId");
            String s1=rs.getString("PlayerName");
            String role=rs.getString("Roles");
            String base=rs.getString("BasePrice");
            String updated=rs.getString("UpdatedPrice");
            String stat=rs.getString("Status");
            String tID=rs.getString("TeamID");
            playerIDLB.setText(pID);
            playerNameLB.setText(s1);
            rolesLB.setText(role);
            bpLB.setText(base);
            currBidLB.setText(updated);
            statLB.setText(stat);
            teamIDLB.setText(tID);
            Bid.setVisible(true);
        }
           else{
               JOptionPane.showMessageDialog(this,"Select an option!"); 
            }
        }
catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_bid1BTNActionPerformed

    private void confirmPayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPayBTNActionPerformed
Payment.setVisible(true);
    }//GEN-LAST:event_confirmPayBTNActionPerformed

    private void bidBackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidBackBTNActionPerformed
Bid.setVisible(false);
PlayerList.setVisible(true);
    }//GEN-LAST:event_bidBackBTNActionPerformed

    private void updatedInfoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedInfoBTNActionPerformed
UpdatedInfo.setVisible(false);
Bid.setVisible(true);
    }//GEN-LAST:event_updatedInfoBTNActionPerformed

    private void walletInfoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walletInfoBTNActionPerformed
WalletInfo.setVisible(false);
    }//GEN-LAST:event_walletInfoBTNActionPerformed

    private void walletStatusBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walletStatusBTNActionPerformed
WalletInfo.setVisible(true);
    }//GEN-LAST:event_walletStatusBTNActionPerformed

    private void walletBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walletBTNActionPerformed
String s=(String)ownerIDTF.getText();
int s1=Integer.parseInt(numberTF.getText());
if(!(s.equals("1") || s.equals("2") || s.equals("3") || s.equals("4") || s.equals("5"))){
    JOptionPane.showMessageDialog(null,"Please enter a valid team ID!");
}
else{
if(s1<=0 || s1>12){
    JOptionPane.showMessageDialog(null,"Please enter a valid number of players!");
}
else{
int prevBid=1500000*s1;
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipl","root","Dragon@2002");
Statement stmt=con.createStatement();
      String query="select * from wallet where ownerid='"+s+"';";
      ResultSet rs=stmt.executeQuery(query);
        if(rs.next()){
            int wallet=rs.getInt("Wallet");
            walletOldLB.setText(""+wallet);
            walletNewLB.setText(""+(wallet-prevBid));
        }
        }
catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}
}
}
    }//GEN-LAST:event_walletBTNActionPerformed

    private void bidAgainBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidAgainBTNActionPerformed
Payment.setVisible(false);
Final.setVisible(false);
UpdatedInfo.setVisible(false);
Bid.setVisible(false);
    }//GEN-LAST:event_bidAgainBTNActionPerformed

    private void paymentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBTNActionPerformed
if((DebitcardjRadioButton.isSelected())||(CreditcardjRadioButton.isSelected()))
{
String card=Cardnumber.getText();
String cvv=new String(CVV.getPassword());
String M=ExpiryMonth.getText();
String Y="20"+ExpiryYear.getText();
int m=Integer.parseInt(M);
int y=Integer.parseInt(Y);
int l1=card.length();
int l2=cvv.length();
Calendar c=Calendar.getInstance();
int month=c.get(Calendar.MONTH)+1;
int year=c.get(Calendar.YEAR);
if(l1!=12 || l2!=3)
{Cardnumber.setText("");
CVV.setText("");
ExpiryMonth.setText("");
ExpiryYear.setText("");
JOptionPane.showMessageDialog(this,"Enter valid card details");
}
   else if(y<year)
       JOptionPane.showMessageDialog(this,"Your card has Expired");
   else if(y==year&&m<month)
       JOptionPane.showMessageDialog(this,"Your card has Expired");
   else
    {
     Final.setVisible(true);
    }
}
  else if((NetbankingjRadioButton.isSelected())||(PaytmjRadioButton.isSelected()))
 {
  Final.setVisible(true);  
 }
    }//GEN-LAST:event_paymentBTNActionPerformed

    private void ExpiryYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpiryYearActionPerformed

    }//GEN-LAST:event_ExpiryYearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if((NetbankingjRadioButton.isSelected())||(PaytmjRadioButton.isSelected()))
{
jLabel37.setVisible(false);
jLabel40.setVisible(false);
jLabel41.setVisible(false);
jLabel42.setVisible(false);
jLabel43.setVisible(false);
Cardnumber.setVisible(false);
ExpiryYear.setVisible(false);
ExpiryMonth.setVisible(false);
Nameoncard.setVisible(false);
CVV.setVisible(false);
}
  else if((DebitcardjRadioButton.isSelected())||(CreditcardjRadioButton.isSelected()))
  {
jLabel37.setVisible(true);
jLabel40.setVisible(true);
jLabel41.setVisible(true);
jLabel42.setVisible(true);
jLabel43.setVisible(true);
Cardnumber.setVisible(true);
ExpiryYear.setVisible(true);
ExpiryMonth.setVisible(true);
Nameoncard.setVisible(true);
CVV.setVisible(true);   
   }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NetbankingjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetbankingjRadioButtonActionPerformed

    }//GEN-LAST:event_NetbankingjRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Bid;
    private javax.swing.JPasswordField CVV;
    private javax.swing.JTextField Cardnumber;
    private javax.swing.JRadioButton CreditcardjRadioButton;
    private javax.swing.JRadioButton DebitcardjRadioButton;
    private javax.swing.JTextField ExpiryMonth;
    private javax.swing.JTextField ExpiryYear;
    private javax.swing.JFrame Final;
    private javax.swing.JTextField Nameoncard;
    private javax.swing.JRadioButton NetbankingjRadioButton;
    private javax.swing.JFrame Payment;
    private javax.swing.JRadioButton PaytmjRadioButton;
    private javax.swing.JFrame PlayerInfo;
    private javax.swing.JFrame PlayerList;
    private javax.swing.JFrame UpdatedInfo;
    private javax.swing.JFrame WalletInfo;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel baseLB;
    private javax.swing.JButton bid1BTN;
    private javax.swing.JButton bidAgainBTN;
    private javax.swing.JButton bidBackBTN;
    private javax.swing.JLabel bpLB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton confirmBidBTN;
    private javax.swing.JButton confirmPayBTN;
    private javax.swing.JLabel currBidLB;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginBTN;
    private javax.swing.JTextField loginTF;
    private javax.swing.JTextField newBidTF;
    private javax.swing.JTextField numberTF;
    private javax.swing.JTextField ownerIDTF;
    private javax.swing.JLabel ownerLB;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton paymentBTN;
    private javax.swing.JLabel pidLB;
    private javax.swing.JLabel playerIDLB;
    private javax.swing.JButton playerInfoBTN;
    private javax.swing.JLabel playerNameLB;
    private javax.swing.JComboBox<String> playerlistCB;
    private javax.swing.JLabel pnameLB;
    private javax.swing.JLabel prevBidLB;
    private javax.swing.JLabel prevTeamIDLB;
    private javax.swing.JLabel roleLB;
    private javax.swing.JLabel rolesLB;
    private javax.swing.JLabel statLB;
    private javax.swing.JLabel statusLB;
    private javax.swing.JLabel teamIDLB;
    private javax.swing.JTextField teamIDTF;
    private javax.swing.JLabel tidLB;
    private javax.swing.JLabel upPlayerIDLB;
    private javax.swing.JLabel upPlayerNameLB;
    private javax.swing.JLabel upStatLB;
    private javax.swing.JLabel updatedBidLB;
    private javax.swing.JButton updatedInfoBTN;
    private javax.swing.JLabel updatedLB;
    private javax.swing.JLabel updatedTeamIDLB;
    private javax.swing.JButton walletBTN;
    private javax.swing.JButton walletInfoBTN;
    private javax.swing.JLabel walletNewLB;
    private javax.swing.JLabel walletOldLB;
    private javax.swing.JButton walletStatusBTN;
    // End of variables declaration//GEN-END:variables
}
